### ISSUE TITLE
Նորմալ ինտերֆեյս նորմալ ձևերով

### ISSUE THREAD

**Issue by antaranyan** [dekanat/aparat#1]
Ցանկալի ա սիրուն, հարմար կարգավորվովի

Ցանկալի չի օգտագործել ֆլեքսգրիդ֊ֆոռվառդ և նման այլ բառեր․

Երեկ փորձեցինք ես, @amuradyan ու քոփայլթ Իքսը, ոչ մի բան չստացվեց․

**Comment by antaranyan** [comment]
Մեթթյու Գրիֆֆիթը իր [Building a Toolkit for Design](https://www.youtube.com/watch?v=Ie-gqwSHQr0) ատենախոսության ընթացքում անդրադառնում է վերը ներկայացված և բազում այլ խնդիրների, տրամադրելով խոստումնալից լուծումներ իր elm-ui մոդուլի շրջանակներում։

<details>
<summary> Որոշ ներկայացում </summary>

| | |
|-|-|
| ![Screenshot 2024-05-08 at 17-12-52 Building a Toolkit for Design by Matthew Griffith](https://github.com/dekanat/aparat/assets/25614707/e5d17608-511d-4eda-87d2-d11e65567b47) | ![Screenshot 2024-05-08 at 17-41-05 Building a Toolkit for Design by Matthew Griffith](https://github.com/dekanat/aparat/assets/25614707/7bb780dd-dd62-4bce-98f3-bd95728ac43b) |
| ![Screenshot 2024-05-08 at 17-13-58 Building a Toolkit for Design by Matthew Griffith](https://github.com/dekanat/aparat/assets/25614707/b6079d8f-b86e-454d-9640-80d2713f7499) | ![Screenshot 2024-05-08 at 17-14-32 Building a Toolkit for Design by Matthew Griffith](https://github.com/dekanat/aparat/assets/25614707/a729e08f-6043-40ce-935d-d1d1ed674320)

</details>

**Comment by amuradyan** [comment]
Չհասցրեցի լսեմ երիտասարդին նորմալ, բայց մենք պարզ բաներին միշտ կողմ ենք։

**Comment by antaranyan** [comment]
Ամեն դեպքում ինտգրել ենք
