### ISSUE TITLE
Ամեն անգամ մի նոր խաղ

### ISSUE THREAD

**Issue by amuradyan** [dekanat/aparat#18]
Որ պահի տակ ուզում եմ մի քիչ հանգստանամ, մտնում եմ ապառատ, հիշում եմ որ նույն խաղն ա տալիս ու տխրում եմ։ 

Բավ է։

#### Անհետաշքիր ապառատի նկարներ։

![aparat2](https://github.com/dekanat/aparat/assets/9533055/8af8361b-7b07-4fa0-ac1d-e4ffb5c5ab2d)
![aparat1](https://github.com/dekanat/aparat/assets/9533055/88607dc0-2e14-484c-a0ed-3b75e866ecef)

**Comment by antaranyan** [comment]
Սա համարենք կատարված #19-ի շրջանակներում
